version: '3.8'

services:
  doc-verifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc-verifier
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: unless-stopped
